{
 "title": "Grafana Dashboard for Veeam Software Appliance",
 "description": "Grafana Dashboard for Veeam Software Appliance using InfluxDB and Prometheus-like metrics (Unofficial)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "backupserver",
    "label": "Backup Server",
    "query": {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node_time_seconds\")\r\n  |> keep(columns: [\"serverName\"])\r\n  |> distinct(column: \"serverName\")\r\n  |> group()"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Veeam Software Appliance Uptime",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"node_time_seconds\" or r._measurement == \"node_boot_time_seconds\")\r\n  |> filter(fn: (r) => r.serverName =~ /${backupserver:regex}/)\r\n  |> group(columns: [\"serverName\",\"instance\",\"version\",\"_measurement\"])\r\n  |> last()\r\n  |> pivot(rowKey: [\"serverName\",\"instance\",\"version\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with _value: r.node_time_seconds - r.node_boot_time_seconds }))\r\n  |> keep(columns: [\"_time\",\"_value\",\"serverName\",\"instance\",\"version\"])\r\n"
    }
   ]
  },
  {
   "title": "Veeam Software Appliance Overview",
   "type": "stat",
   "description": "This panel displays all the needed Veeam Software Appliance information of the unit you are running.",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.serverName =~ /${backupserver:regex}/)\r\n  |> filter(fn: (r) => r._measurement == \"node_time_seconds\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ r with _value: r.serverName }))\r\n  |> keep(columns: [\"_time\",\"_value\"])"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.serverName =~ /${backupserver:regex}/)\r\n  |> filter(fn: (r) => r._measurement == \"node_time_seconds\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ r with _value: r.version }))\r\n  |> keep(columns: [\"_time\",\"_value\"])\r\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.serverName =~ /${backupserver:regex}/)\r\n  |> filter(fn: (r) => r._measurement == \"node_memory_MemTotal_bytes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> last()\r\n  |> map(fn: (r) => ({ r with _value: r._value / 1073741824.0 }))\r\n  |> keep(columns: [\"_time\",\"_value\"])\r\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.serverName =~ /${backupserver:regex}/)\r\n  |> filter(fn: (r) => r._measurement == \"node_cpu_seconds_total\" and r.cpu != \"all\")\r\n  |> group(columns: [\"serverName\",\"cpu\"])\r\n  |> last()\r\n  |> group(columns: [\"serverName\"])\r\n  |> keep(columns: [\"_time\",\"cpu\"])\r\n  |> distinct(column: \"cpu\")\r\n  |> count()\r\n  |> map(fn: (r) => ({ r with _field: \"logical_cores\" }))\r\n  |> keep(columns: [\"_time\",\"_value\",\"_field\"])"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.serverName =~ /${backupserver:regex}/)\r\n  |> filter(fn: (r) => r._measurement == \"node_disk_reads_completed_total\")\r\n  |> keep(columns: [\"device\",\"_time\"])\r\n  |> distinct(column: \"device\")\r\n  |> count()\r\n  |> keep(columns: [\"_time\",\"_value\"])\r\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.serverName =~ /${backupserver:regex}/)\r\n  |> filter(fn: (r) => r._measurement == \"node_network_receive_bytes_total\")\r\n  |> keep(columns: [\"interface\",\"_time\"])\r\n  |> distinct(column: \"interface\")\r\n  |> count()\r\n  |> keep(columns: [\"_time\",\"_value\"])\r\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.serverName =~ /${backupserver:regex}/)\r\n  |> filter(fn: (r) => r._measurement == \"node_memory_SwapTotal_bytes\" or r._measurement == \"node_memory_SwapFree_bytes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\",\"serverName\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with _value: 100.0 * (1.0 - float(v: r.node_memory_SwapFree_bytes) / float(v: r.node_memory_SwapTotal_bytes)) }))\r\n  |> keep(columns: [\"_time\",\"_value\",\"serverName\"])\r\n"
    }
   ]
  },
  {
   "title": "Latest Data Collection",
   "type": "stat",
   "description": "Latest Data Collection",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement =~ /^node_/)\r\n  |> filter(fn: (r) => r[\"host\"] =~ /${backupserver:regex}/ or r[\"serverName\"] =~ /${backupserver:regex}/ or r[\"instance\"] =~ /${backupserver:regex}/)\r\n  |> group()\r\n  |> last()\r\n  |> map(fn: (r) => ({ r with _time: now(), _value: float(v: uint(v: r._time)) / 1000000.0 }))\r\n  |> keep(columns: [\"_time\",\"_value\"])\r\n"
    }
   ]
  },
  {
   "title": "Veeam Software Appliance - CPU Usage in %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"node_cpu_seconds_total\")\r\n  |> filter(fn: (r) => r.serverName =~ /${backupserver:regex}/ or r.instance =~ /${backupserver:regex}/)\r\n  |> group(columns: [\"serverName\",\"instance\",\"version\",\"cpu\",\"mode\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> pivot(rowKey: [\"_time\",\"serverName\",\"instance\",\"version\",\"cpu\"], columnKey: [\"mode\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with total: r.user + r.nice + r.system + r.irq + r.softirq + r.steal + r.guest + r.guest_nice + r.iowait + r.idle }))\r\n  |> map(fn: (r) => ({ r with _value: if r.total > 0.0 then (r.total - r.idle - r.iowait) / r.total * 100.0 else 0.0 }))\r\n  |> keep(columns: [\"_time\",\"_value\",\"serverName\",\"instance\",\"version\",\"cpu\"])\r\n"
    }
   ]
  },
  {
   "title": "Veeam Software Appliance - RAM Usage in %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.serverName =~ /${backupserver:regex}/)\r\n  |> filter(fn: (r) => r._measurement == \"node_memory_MemTotal_bytes\" or r._measurement == \"node_memory_MemAvailable_bytes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> group(columns: [\"serverName\",\"instance\",\"version\",\"_measurement\"])\r\n  |> pivot(rowKey: [\"_time\",\"serverName\",\"instance\",\"version\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with _value: (1.0 - r.node_memory_MemAvailable_bytes / r.node_memory_MemTotal_bytes) * 100.0 }))\r\n  |> keep(columns: [\"_time\",\"_value\",\"serverName\",\"instance\",\"version\"])\r\n  |> yield(name: \"mem_used_pct\")\r\n"
    }
   ]
  },
  {
   "title": "Veeam Software Appliance - Network Usage - Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.serverName =~ /${backupserver:regex}/)\r\n  |> filter(fn: (r) => r._measurement == \"node_network_transmit_bytes_total\")\r\n  |> filter(fn: (r) => exists r.interface and r.interface != \"\")\r\n  |> group(columns: [\"serverName\",\"interface\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> keep(columns: [\"_time\",\"_value\",\"serverName\",\"interface\"])\r\n  |> yield(name: \"tx B/s\")\r\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.serverName =~ /${backupserver:regex}/)\r\n  |> filter(fn: (r) => r._measurement == \"node_network_receive_bytes_total\")\r\n  |> filter(fn: (r) => exists r.interface and r.interface != \"\")\r\n  |> group(columns: [\"serverName\",\"interface\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> keep(columns: [\"_time\",\"_value\",\"serverName\",\"interface\"])\r\n  |> yield(name: \"rx B/s\")\r\n"
    }
   ]
  },
  {
   "title": "Veeam Software Appliance - Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.serverName =~ /${backupserver:regex}/)\r\n  |> filter(fn: (r) => r._measurement == \"node_disk_read_bytes_total\")\r\n  |> filter(fn: (r) => exists r.device and r.device != \"\")\r\n  |> group(columns: [\"serverName\",\"device\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> set(key: \"_field\", value: \"read_bps\")\r\n  |> keep(columns: [\"_time\",\"_value\",\"serverName\",\"device\",\"_field\"])\r\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.serverName =~ /${backupserver:regex}/)\r\n  |> filter(fn: (r) => r._measurement == \"node_disk_written_bytes_total\")\r\n  |> filter(fn: (r) => exists r.device and r.device != \"\")\r\n  |> group(columns: [\"serverName\",\"device\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> set(key: \"_field\", value: \"write_bps\")\r\n  |> keep(columns: [\"_time\",\"_value\",\"serverName\",\"device\",\"_field\"])\r\n"
    }
   ]
  },
  {
   "title": "Veam Software Appliance - Volume Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.serverName =~ /${backupserver:regex}/)\r\n  |> filter(fn: (r) => r._measurement == \"node_filesystem_size_bytes\" or r._measurement == \"node_filesystem_free_bytes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> pivot(rowKey: [\"_time\",\"serverName\",\"instance\",\"version\",\"device\",\"fstype\",\"mountpoint\"], columnKey: [\"_measurement\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with _value: 100.0 * (1.0 - (float(v: r.node_filesystem_free_bytes) / float(v: r.node_filesystem_size_bytes))) }))\r\n  |> keep(columns: [\"_time\",\"_value\",\"serverName\",\"device\",\"fstype\",\"mountpoint\"])\r\n  |> group(columns: [\"serverName\",\"mountpoint\"])\r\n"
    }
   ]
  }
 ]
}